name: cloudlisten
description: Application to upload and listen to songs from the cloud

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
  firebase_auth:
  file_picker:
  cloud_firestore: 
  audioplayers:
  provider:
  connectivity:
  flare_flutter:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "launchericon.jpg"

flutter:
  uses-material-design: true
  assets:
    - animations/
    - launchericon.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
